version: 2
jobs:
  checkout_and_install:
    docker:
      - image: circleci/node:8.10.0-browsers
    steps:
      - add_ssh_keys
      - restore_cache:
          keys:
            - source-cache-{{ .Branch }}-{{ .Revision }}
            - source-cache-{{ .Branch }}-
            - source-cache-
      - checkout
      - save_cache:
          key: source-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - restore_cache:
          keys:
            - dep-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dep-cache-{{ .Branch }}
      - run: echo 'export PATH=node_modules/.bin:$PATH' >> $BASH_ENV
      - run: npm install yarn
      - run: yarn
      - save_cache:
          key: dep-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  tests:
    docker:
      - image: circleci/node:8.10.0-browsers
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run: echo 'export PATH=node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run tests.
          command: npm test

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - checkout_and_install

      - tests:
          requires:
            - checkout_and_install
